DELETE FROM alternateNames WHERE alternateNames.isolanguage IN ('ar', 'ara') AND alternateNames.geonameid IN (347542, 347612, 347634, 347749, 348112, 349156, 349717, 350376, 350422, 351434, 352354, 352628, 352679, 352913, 352951, 353219, 353802, 353828, 354365, 354775, 354981, 355026, 355392, 355420, 355628, 355648, 356000, 356806, 356933, 356989, 358108, 358115, 358269, 358274, 358600, 358970, 359212, 359710, 359900, 359953, 360048, 360464, 360526, 360531, 360754, 360773, 360928, 361029, 361179, 361329, 361394, 361435, 361478, 361495, 361661, 361827, 362004, 362277, 362882, 362973, 411165, 7521348, 361457, 360502, 361213, 361546, 359792, 359783, 359576, 358821, 358048, 361546, 355939, 350550, 349114, 347796, 347796, 347796, 347236, 362485, 361702, 359792, 359783, 359576, 355449, 360502, 361103, 361058, 361055, 360502, 361457, 360995, 361213, 360923, 419435, 359493, 359796, 361546, 361291, 361320, 360630, 360542, 360615, 360612, 360829, 360716, 360761, 360686, 358840, 358821, 359280, 359173, 358619, 358619, 355795, 358172, 358448, 358048, 358095, 350203, 346030, 358620, 349715, 347796, 359796, 349158, 349114, 347591, 347497, 347236, 356945, 350789, 350550, 350370, 354502, 354105, 361320, 361055, 352733, 360761, 352344, 355939);

INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (347542, 'ar', 'طامية', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (347612, 'ar', 'تلا', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (347634, 'ar', 'طهطا', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (347749, 'ar', 'سمسطا الوقف', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (348112, 'ar', 'سيدي سالم', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (349156, 'ar', 'شبين القناطر', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (349717, 'ar', 'سمالوط', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (350376, 'ar', 'قطور', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (350422, 'ar', 'قوص', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (351434, 'ar', 'نجع حمادي', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (352354, 'ar', 'منوف', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (352628, 'ar', 'مطاي', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (352679, 'ar', 'مشتول السوق', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (352913, 'ar', 'منفلوط', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (352951, 'ar', 'ملوي', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (353219, 'ar', 'مدينة السادس من أكتوبر', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (353802, 'ar', 'كوم أمبو', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (353828, 'ar', 'كوم حمادة', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (354365, 'ar', 'كفر الزيات', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (354775, 'ar', 'كفر الدوار', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (354981, 'ar', 'جهينة', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (355026, 'ar', 'جرجا', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (355392, 'ar', 'عزبة البرج', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (355420, 'ar', 'إطسا', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (355628, 'ar', 'إدكو', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (355648, 'ar', 'إبشواي', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (356000, 'ar', 'حوش عيسى', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (356806, 'ar', 'فوه', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (356933, 'ar', 'فرشوط', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (356989, 'ar', 'فاقوس', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (358108, 'ar', 'دسوق', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (358115, 'ar', 'دشنا', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (358269, 'ar', 'ديروط', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (358274, 'ar', 'دير مواس', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (358600, 'ar', 'ناصر', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (358970, 'ar', 'بسيون', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (359212, 'ar', 'بني مزار', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (359710, 'ar', 'التل الكبير', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (359900, 'ar', 'الصف', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (359953, 'ar', 'الشهداء', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (360048, 'ar', 'أشمون', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (360464, 'ar', 'الواسطى', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (360526, 'ar', 'القوصية', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (360531, 'ar', 'القصير', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (360754, 'ar', 'المنزلة', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (360773, 'ar', 'المنشاة', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (360928, 'ar', 'الخانكة', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (361029, 'ar', 'البصراط', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (361179, 'ar', 'الحوامدية', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (361329, 'ar', 'الفشن', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (361394, 'ar', 'الباويطي', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (361435, 'ar', 'البلينا', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (361478, 'ar', 'البداري', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (361495, 'ar', 'العياط', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (361661, 'ar', 'أخميم', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (361827, 'ar', 'الدلنجات', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (362004, 'ar', 'أبو تيج', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (362277, 'ar', 'ابوقرقاص', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (362882, 'ar', 'أبو المطامير', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (362973, 'ar', 'أبنوب', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (411165, 'ar', 'إدفو', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (7521348, 'ar', 'العين السخنة', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (360502, 'ar', 'الأقصر', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (361213, 'ar', 'الحامول', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (359792, 'ar', 'أسوان', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (359783, 'ar', 'أسيوط', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (359576, 'ar', 'أوسيم', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (358821, 'ar', 'بلقاس', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (358048, 'ar', 'دمياط', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (355939, 'ar', 'ههيا', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (350550, 'ar', 'قنا', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (347796, 'ar', 'سوهاج', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (347236, 'ar', 'طوخ', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (362485, 'ar', 'أبو كبير', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (361702, 'ar', 'أجا', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (355449, 'ar', 'إسنا', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (361103, 'ar', 'الإبراهيمية', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (361058, 'ar', 'الإسكندرية', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (361055, 'ar', 'الإسماعيلية', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (361457, 'ar', 'الباجور', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (360995, 'ar', 'الجيزة', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (360923, 'ar', 'الخارجة', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (419435, 'ar', 'الزرقا', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (359493, 'ar', 'الزقازيق', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (361546, 'ar', 'العريش', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (361291, 'ar', 'الغردقة', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (361320, 'ar', 'الفيوم', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (360630, 'ar', 'القاهرة', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (360542, 'ar', 'القرين', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (360615, 'ar', 'القناطر الخيرية', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (360612, 'ar', 'القنايات', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (360829, 'ar', 'المحلة الكبرى', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (360716, 'ar', 'المطرية', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (360761, 'ar', 'المنصورة', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (360686, 'ar', 'المنيا', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (358840, 'ar', 'بلبيس', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (359280, 'ar', 'بنها', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (359173, 'ar', 'بني سويف', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (358619, 'ar', 'بورسعيد', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (355795, 'ar', 'حلوان', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (358172, 'ar', 'دكرنس', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (358448, 'ar', 'دمنهور', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (358095, 'ar', 'ديرب نجم', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (350203, 'ar', 'رشيد', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (346030, 'ar', 'زفتى', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (358620, 'ar', 'سفاجا', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (349715, 'ar', 'سمنود', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (347796, 'ar', 'سوهاج', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (359796, 'ar', 'سويس', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (349158, 'ar', 'شبين الكوم', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (349114, 'ar', 'شربين', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (347591, 'ar', 'طلخا', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (347497, 'ar', 'طنطا', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (347236, 'ar', 'طوخ', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (356945, 'ar', 'فارسكور', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (350789, 'ar', 'قليوب', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (350370, 'ar', 'قويسنا', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (354502, 'ar', 'كفر الشيخ', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (354105, 'ar', 'كفر صقر', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (352733, 'ar', 'مرسى مطروح', NULL, NULL, NULL, NULL);
INSERT INTO alternateNames (geonameid, isolanguage, alternate_name, isPreferredName, isShortName, isColloquial, isHistoric) VALUES (352344, 'ar', 'منية النصر', NULL, NULL, NULL, NULL);